spring:
  cloud:
    config:
      server:
        native:
          search-locations: >
            classpath:shared/cloud,
            classpath:shared/database,
            classpath:config/service/helloworld1,
            classpath:config/service/helloworld2,
            classpath:config/service/authserver
